// Background images live in src/lib/assets/backgrounds. import.meta.glob lets
// Vite bundle them (single hashed copy each) and gives us their resolved URLs.
// Drop a new image in that folder and it's picked up automatically.
const modules = import.meta.glob<string>('../assets/backgrounds/*.{png,jpg,jpeg,webp,avif}', {
  eager: true,
  query: '?url',
  import: 'default',
})

// Small copies for the settings picker, generated by `npm run thumbs` and
// matched to their background by file name. Optional: an image with no
// thumbnail falls back to the full-size one, so a new file still works before
// the script is run — it's just heavier to render in the grid.
const thumbnails = import.meta.glob<string>(
  '../assets/backgrounds/thumbnails/*.{png,jpg,jpeg,webp,avif}',
  { eager: true, query: '?url', import: 'default' },
)

const thumbnailsByName: Record<string, string> = Object.fromEntries(
  Object.entries(thumbnails).map(([path, url]) => {
    const file = path.split('/').pop() ?? path
    return [file.replace(/\.[^.]+$/, ''), url]
  }),
)

// The place each (AI-generated) scene evokes, keyed by file name. Optional —
// an image with no entry here just shows no caption, so dropping in a new file
// still works without touching this map.
const locations: Record<string, string> = {
  "china-jiuzhaigou.avif": "Jiuzhaigou Valley, Sichuan • China",
  "china-zhangjiajie.avif": "Zhangjiajie National Forest Park, Hunan • China",
  "china.avif": "Li River, Guangxi • China",
  "croatia.avif": "Plitvice Lakes National Park, Lika-Senj • Croatia",
  "egypt.avif": "Nile River at Luxor • Egypt",
  "guatemala.avif": "Semuc Champey, Alta Verapaz • Guatemala",
  "indonesia-sumatra.avif": "Tea Plantation, Kerinci Valley, Sumatra • Indonesia",
  "indonesia.avif": "Diamond Beach, Nusa Penida • Indonesia",
  "italy.avif": "Lago di Carezza, Dolomites • Italy",
  "japan-kyoto.avif": "Cherry Blossoms over Kamo River, Kyoto • Japan",
  "madagascar.avif": "Avenue of the Baobabs, Menabe • Madagascar",
  "mexico.avif": "Cenote Ik Kil, Yucatán • Mexico",
  "morocco.avif": "Legzira Beach, Sidi Ifni • Morocco",
  "new-zealand.avif": "Moeraki Boulders, Koekohe Beach • New Zealand",
  "seychelles.avif": "Anse Source d'Argent, La Digue Island • Seychelles",
  "switzerland.avif": "Lauterbrunnen Valley, Bernese Oberland • Switzerland",
  "thailand.avif": "Cheow Lan Lake, Khao Sok • Thailand",
  "united-kingdom.avif": "Epping Forest, Essex • United Kingdom",
  "vietnam.avif": "Trang An, Ninh Bình • Vietnam",
  "yemen.avif": "Dragon Trees, Dixam Plateau, Socotra • Yemen",
}

/** A bundled background image, plus the place its scene evokes if we have one. */
export interface Background {
  /** File name, e.g. `japan.avif`. Stable across builds, unlike the hashed url,
      so it's what saved preferences refer to. */
  id: string
  url: string
  /** Small copy for grids and lists; the full-size url when none was generated. */
  thumbUrl: string
  location?: string
}

/**
 * Every bundled background, and the order the settings picker lists them in:
 * the order of the `locations` map above, so re-ordering that map re-orders the
 * picker. Images with no entry there follow, by file name.
 */
export const backgrounds: Background[] = (() => {
  const byId = new Map<string, Background>()
  for (const path of Object.keys(modules).sort()) {
    const id = path.split('/').pop() ?? path
    const url = modules[path]
    byId.set(id, {
      id,
      url,
      thumbUrl: thumbnailsByName[id.replace(/\.[^.]+$/, '')] ?? url,
      location: locations[id],
    })
  }

  const listed = Object.keys(locations)
    .map((id) => byId.get(id))
    .filter((b): b is Background => b !== undefined)
  const rest = [...byId.values()].filter((b) => !(b.id in locations))

  return [...listed, ...rest]
})()

/**
 * The images a random pick may draw from. `ids` is the user's chosen set: an
 * empty selection (or one naming only images that no longer ship) means "no
 * preference", which is every background rather than none.
 */
export function backgroundPool(ids?: string[]): Background[] {
  if (!ids || ids.length === 0) return backgrounds
  const chosen = backgrounds.filter((b) => ids.includes(b.id))
  return chosen.length > 0 ? chosen : backgrounds
}

/** Whether `background` is one the user's current selection allows. */
export function isInPool(background: Background | undefined, ids?: string[]): boolean {
  return !!background && backgroundPool(ids).some((b) => b.id === background.id)
}

/**
 * A random background from the user's chosen set, or undefined if there are
 * none. Pass the one currently on screen to be sure of getting a different
 * image back — useful for a manual refresh, where landing on the same picture
 * would read as a broken button. Ignored when the set holds only that image.
 */
export function randomBackground(exclude?: Background, ids?: string[]): Background | undefined {
  const choices = backgroundPool(ids)
  const others = exclude ? choices.filter((b) => b.id !== exclude.id) : choices
  const from = others.length > 0 ? others : choices
  if (from.length === 0) return undefined
  return from[Math.floor(Math.random() * from.length)]
}
